//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMain.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Transmission { get; set; }
        public string GazType { get; set; }
        public double EngineLitres { get; set; }
        public string TypeOfCar { get; set; }
        public int CarManufacturerId { get; set; }
        public int Discount { get; set; }
        public string Photos { get; set; }
        public double Price { get; set; }
    
        public virtual CarManufacturer CarManufacturer { get; set; }
    }
}
