//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMain.EF
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Accounts
    {
        public string Login { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }

        private static Accounts instance;

        public Accounts() { }

        private Accounts(string login, string email, string password, bool isAdmin)
        {
            Login = login;
            Email = email;
            Password = password;
            IsAdmin = isAdmin;
        }

        public static Accounts GetInstance(string login, string email, string password, bool IsAdmin)
        {
            if (instance == null)
                instance = new Accounts(login, email, password, IsAdmin);

            return instance;
        }

        public static List<Accounts> GetAccounts()
        {
            CarsDBEntities1 context = new CarsDBEntities1();
            var res = new List<Accounts>();

            var test = context.Accounts
                .Select(e => new
                {
                    login = e.Login,
                    password =  e.Password,
                    email = e.Email,
                    isadmin = e.IsAdmin
                });


            foreach (var item in test)
            {
                res.Add(new Accounts { Login = item.login, Password = item.password, Email = item.email, IsAdmin = item.isadmin});
            }
            return res;
        }
    }
}
