//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        public string Owner { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public float Price { get; set; }
        public int Discount { get; set; }
        public Nullable<int> CarId { get; set; }
    }
}
