//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMain
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Cars
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Transmission { get; set; }
        public string GazType { get; set; }
        public double EngineLitres { get; set; }
        public string TypeOfCar { get; set; }
        public int CarManufacturerId { get; set; }
        public int Discount { get; set; }
        public string Photo1 { get; set; }
        public double Price { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
    
        public virtual CarManufacturer CarManufacturer { get; set; }

        public override string ToString()
        {
            return $"{Model}";
        }


        public static List<Cars> getCars()
        {
            CarsDBEntities context = new CarsDBEntities();
            var res = new List<Cars>();

            var test = context.Cars
                .Where(e => e.Id != 0)
                .Select(e => new
                {
                    name = e.Name,
                    model = e.Model,
                    transmission = e.Transmission,
                    gaztype = e.GazType,
                    enginelitres = e.EngineLitres,
                    typeofcar = e.TypeOfCar,
                    discount = e.Discount,
                    photo1 = e.Photo1,
                    price = e.Price,
                    photo2 = e.Photo2,
                    photo3 = e.Photo3
                });


            foreach (var item in test)
            {
                res.Add(new Cars { Name = item.name, Model = item.model, Transmission = item.transmission, GazType = item.gaztype, EngineLitres = item.enginelitres, TypeOfCar = item.typeofcar, Discount = item.discount, Photo1 = item.photo1, Price = item.price, Photo2 = item.photo2, Photo3 = item.photo3 });
            }
            return res;
        }
    }
}
